# Aider configuration file

# Files to read at startup
read:
  - CONVENTIONS.md

model: groq/deepseek-r1-distill-llama-70b
editor-model: openrouter/anthropic/claude-3.7-sonnet
weak-model: groq/deepseek-r1-distill-llama-70b-specdec
edit-format: diff
editor-edit-format: editor-diff
cache-prompts: true
stream: true 

extra-params:
  max_tokens: 160000

