cache-prompts: true
auto-test: true

read:
  - CONVENTIONS.md
  - VIBE.md
  - GOALS.md
  - README.md
  - tests/deploy.feature

lint-cmd:
  - "python: pyright"

test-cmd: uv run poe dev

alias:
  - sonnet:openrouter/anthropic/claude-3.7-sonnet
  - dsdistill:groq/deepseek-r1-distill-llama-70b
  - deepseek:openrouter/deepseek/deepseek-r1
  - gemini:openrouter/google/gemini-2.0-flash-001
  - thinking:openrouter/anthropic/claude-3.7-sonnet:thinking
  - help:openrouter/google/gemini-2.0-flash-001
  - anth:anthropic/claude-3-sonnet
  - anthor:openrouter/anthropic/claude-3.7-sonnet
  - ds:deepseek/deepseek-r1
  - dsor:openrouter/deepseek/deepseek-r1
