# Aider configuration file

# Files to read at startup
read:
  - CONVENTIONS.md

# Model configuration (exact parameters from official docs)
model: openrouter/anthropic/claude-3.7-sonnet
weak-model: openrouter/deepseek/deepseek-r1
editor-model: openrouter/deepseek/deepseek-chat
edit-format: diff
editor-edit-format: editor-diff
# Validated Claude parameters from docs
extra-params:
  max_tokens: 64000
  extra_headers:
    anthropic-beta: tools-2024-04-04
