cache-prompts: true
auto-test: false

read:
  - PROJECT_STRUCTURE.md
  - CONVENTIONS.md
  - VIBE.md
  - GOALS.md
  - README.md
  - tests/deploy.feature

lint-cmd:
  - "python: pyright"

test-cmd: uv run poe dev

alias:
  - son:anthropic/claude-3.7-sonnet
  - sonor:openrouter/anthropic/claude-3.7-sonnet
  - sontor:openrouter/anthropic/claude-3.7-sonnet:thinking
  - ds:deepseek/deepseek-r1
  - dsor:openrouter/deepseek/deepseek-r1
  - dsllama:groq/deepseek-r1-distill-llama-70b
  - gem:openrouter/google/gemini-2.0-flash-001
  - rr:openrouter/sophosympatheia/rogue-rose-103b-v0.2:free"
