# Aider configuration file

# Files to read at startup
read:
  - CONVENTIONS.md

# Model configuration (exact parameters from official docs)
model: openrouter/anthropic/claude-3.7-sonnet
weak-model: openrouter/deepseek/deepseek-r1
editor-model: openrouter/deepseek/deepseek-chat
edit-format: diff
editor-edit-format: editor-diff
# Validated Claude parameters from docs
extra-params:
  max_tokens: 64000
  thinking_tokens: 32000  # Enable thinking tokens for optimal performance (64.9% correct on benchmark)
  extra_headers:
    anthropic-beta: prompt-caching-2024-07-31,pdfs-2024-09-25,output-128k-2025-02-19

# Alternative high-performance setup (uncomment to use):
# Use this command instead for architect pattern:
# aider --architect --model openrouter/deepseek/deepseek-r1 --editor-model openrouter/anthropic/claude-3.5-sonnet
