[project]
name = "deploy"
version = "1.0.0"
requires-python = ">=3.12"

dependencies = ["poethepoet", "pytest-bdd", "pyinfra"]

[tool.poe.tasks.dev]
cmd = "pytest -x --gherkin-terminal-reporter --tb=no -s -v -m dev tests/"

[tool.poe.tasks.ci]
cmd = "pytest -x --tb=long -s -v -m ci tests/"

[tool.poe.tasks.ai]
envfile = ".env.aider"
cmd = "aider --architect"

[tool.poe.tasks.ai1]
envfile = ".env.aider"
cmd = "aider --watch-files --model r1 --editor-model sonnet"

[tool.poe.tasks.ai2]
envfile = ".env.aider"
cmd = "aider --watch-files --model sonnet"

[tool.poe.tasks.ai3]
envfile = ".env.aider"
cmd = "aider --watch-files --no-show-model-warnings --model groq/deepseek-r1-distill-llama-70b-specdec"

[tool.poe.tasks.ai4]
envfile = ".env.aider"
cmd = "aider --watch-files --no-show-model-warnings --model groq/deepseek-r1-distill-qwen-32b"

[tool.poe.tasks.ai5]
envfile = ".env.aider"
cmd = "aider --watch-files --no-show-model-warnings --model r1 --editor-model groq/deepseek-r1-distill-qwen-32b"

[tool.poe.tasks.ai6]
envfile = ".env.aider"
cmd = "aider --watch-files --no-show-model-warnings --model groq/deepseek-r1-distill-llama-70b-specdec --editor-model sonnet"

[tool.poe.tasks.ai7]
envfile = ".env.aider"
cmd = "aider --watch-files --no-show-model-warnings --model groq/deepseek-r1-distill-qwen-32b --editor-model sonnet"

[tool.poe.tasks.ai8]
envfile = ".env.aider"
cmd = "aider --watch-files --model openrouter/anthropic/claude-3.7-sonnet:thinking"

[tool.pytest.ini_options]
markers = [
  "dev",
  "ci",
  "prod"
]

filterwarnings = [
  "ignore::DeprecationWarning"
]

