apiVersion: apps/v1
kind: Deployment
metadata:
  name: target
spec:
  selector:
    matchLabels:
      app: target
  template:
    metadata:
      labels:
        app: target
    spec:
      containers:
      - name: target
        image: target:latest
        ports:
        - containerPort: 2222
        - containerPort: 8000
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: ssh-service
spec:
  clusterIP: None
  ports:
  - port: 2222
    targetPort: 2222
  selector:
    app: target
---
apiVersion: v1
kind: Service
metadata:
  name: saleor-api-service
spec:
  clusterIP: None
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: target
---
apiVersion: v1
kind: Service
metadata:
  name: saleor-dashboard-service
spec:
  clusterIP: None
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: target
